### ISSUE TITLE
Add User - Name Input - Control Chartater Issue

### ISSUE THREAD

**Issue by JeffryWeigel** [ikygoose/arch-installer#52]
When adding a user and entering the user name, control characters such as backspace did not remove a character and instead added a ^? (? = whatever letter it was) to the name. I assume the password entry would have the same issue, but didn't test.

**Comment by JeffryWeigel** [comment]
Verified, it also happens with the user password input and found it happens in the computer name input as well.

**Comment by ikygoose** [comment]
I can't seem to reproduce this on my test machine, could this be an issue with your laptop's function buttons?

**Comment by JeffryWeigel** [comment]
hmm, I will check that

**Comment by ikygoose** [comment]
Issue was due to using the incorrect key map for the keyboard in question
